apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-http
spec:
  entryPoints:
    - web
  routes:
    - match: (ClientIP(`192.168.0.0/16`)) && HeaderRegexp(`Cookie`, `app_route=n8n`)
      kind: Rule
      services:
        - name: n8n
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: (ClientIP(`192.168.0.0/16`)) && HeaderRegexp(`Cookie`, `app_route=n8n`)
      kind: Rule
      services:
        - name: n8n
          port: 80
  tls:
    secretName: generic-certificate
